import express from 'express';
import { errorHandler } from './middlewares/error-handler';
import { paymentController } from './controllers/payment-controller';
import { paymentRouter } from './routes/payment-routes';
import { subscriptionRouter } from './routes/subscription-routes';
import { subscriptionController } from './controllers/subscription-controller';
import { requireInternalService } from './middlewares/internal-auth';
export const app = express();
app.disable('x-powered-by');
app.get('/health', (_request, response) => response.json({ success: true, message: 'Payment service is healthy', data: { service: 'payment-service' } }));
app.post('/webhooks/stripe', express.raw({ type: 'application/json' }), paymentController.webhook);
app.use(express.json());
app.get('/internal/subscriptions/:userId', requireInternalService, (request, response, next) => { void subscriptionController.internalMembership(request, response).catch(next); });
app.use('/api/payments', paymentRouter);
app.use('/api/subscriptions', subscriptionRouter);
app.use(errorHandler);
